services:
  backend:
    build: ./backend
    command: uvicorn src.app:app --host 0.0.0.0 --reload --port 8000
    container_name: backend
    volumes:
      - ./backend:/backend
    env_file: ".env"
    ports:
      - "8000:8000"
    depends_on:
      - backend-db

  backend-worker:
    build: ./backend
    command: [ 'celery', '-A', 'src.tasks.celery_app', 'worker', '-l', 'info' ]
    container_name: backend-worker
    env_file: ".env"
    volumes:
      - ./backend:/backend
    depends_on:
      - backend-db

  backend-db:
    image: postgres:17
    container_name: backend-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES__USER}
      - POSTGRES_PASSWORD=${POSTGRES__PASSWORD}
      - POSTGRES_DB=${POSTGRES__DB}
      - POSTGRES_PORT=${POSTGRES__PORT}
    volumes:
      - backend-db-volume:/var/lib/postgresql/data

  backend-redis:
    image: redis:7
    container_name: backend-redis

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"
    env_file: ".env"

volumes:
  backend-db-volume:
